
language: node_js

node_js:
  - "node"

before_install:
  - rm -fr node_modules
  - npm install terser jshint colors yargs readline-sync

script:
  - npm run build-creator-node
  - npm run test-creator-node

